import 'package:car_faults_app/l10n/app_localizations.dart';

/// Fuel types offered by the search form.
///
/// UI enum with en-GB naming, matching the web app's fuel list
/// (`gasoline`/`gpl` there, `petrol`/`lpg` here).
enum FuelOption { petrol, diesel, electric, lpg, hybrid }

extension FuelOptionLabel on FuelOption {
  String label(AppLocalizations l10n) => switch (this) {
    FuelOption.petrol => l10n.homeFuelPetrol,
    FuelOption.diesel => l10n.homeFuelDiesel,
    FuelOption.electric => l10n.homeFuelElectric,
    FuelOption.lpg => l10n.homeFuelLpg,
    FuelOption.hybrid => l10n.homeFuelHybrid,
  };
}

/// Mocked option lists of the vehicle search form.
///
/// [brands] and [doors] mirror the web app (`lib/mocks/vehicle-makes.ts` and
/// the door options of `components/home/vehicle-search-form.tsx`). A real
/// catalogue endpoint replaces this later.
abstract final class HomeSearchOptions {
  static const doors = <int>[2, 3, 4, 5];
  static const oldestYear = 1900;

  /// Newest first, down to [oldestYear]. Next year is included because models
  /// reach the market before their model year starts.
  static List<int> years() {
    final newestYear = DateTime.now().year + 1;
    return [for (var year = newestYear; year >= oldestYear; year--) year];
  }

  /// Case-insensitive substring match, same rule as the web app's
  /// `filterVehicleMakes`. An empty query offers every make.
  static List<String> filterBrands(String query) {
    final normalizedQuery = query.trim().toLowerCase();
    if (normalizedQuery.isEmpty) return brands;

    return [
      for (final brand in brands)
        if (brand.toLowerCase().contains(normalizedQuery)) brand,
    ];
  }

  static const brands = <String>[
    'Abarth',
    'AC Cars',
    'Acura',
    'AGB IPA',
    'Agrale',
    'Aion',
    'Aito',
    'Aiways',
    'Aixam',
    'Alba',
    'Alfa Romeo',
    'Alpine',
    'Aprilia',
    'Arrinera',
    'Ashok Leyland',
    'Aston Martin',
    'Ather',
    'Audi',
    'Avatr',
    'Bajaj',
    'Baojun',
    'BEN',
    'Bentley',
    'BMW',
    'Brabham',
    'Buick',
    'BYD',
    'Cadillac',
    'CAOA Chery',
    'CFMOTO',
    'Changan',
    'Chery',
    'Chevrolet',
    'Chirey',
    'Chrysler',
    'Citroën',
    'Cupra',
    'Cyclone Motor',
    'Dacia',
    'Daewoo',
    'Dafra',
    'Daihatsu',
    'Deepal',
    'Denza',
    'Derbi',
    'Deutz-Fahr',
    'DM',
    'Dodge',
    'Dongfeng',
    'DS',
    'Ducati',
    'Edfor',
    'Effa',
    'Elfin',
    'Felcom',
    'Fendt',
    'Ferrari',
    'Fiat',
    'Force Motors',
    'Ford',
    'FPV',
    'FSO',
    'GAC',
    'Geely',
    'Genesis',
    'GMC',
    'Great Wall',
    'Gurgel',
    'GWM',
    'Haojue',
    'Harley-Davidson',
    'Haval',
    'Hero',
    'Hindustan Motors',
    'Holden',
    'Honda',
    'Hongqi',
    'HSV',
    'Hummer',
    'Hyundai',
    'Indian',
    'Infiniti',
    'Inokom',
    'Isuzu',
    'Italika',
    'Iveco',
    'Izera',
    'JAC',
    'Jaecoo',
    'Jaguar',
    'Jeep',
    'Jetour',
    'John Deere',
    'Kawasaki',
    'Keeway',
    'KGM',
    'Kia',
    'KTM',
    'Lada',
    'Lamborghini',
    'Lancia',
    'Land Rover',
    'LDV',
    'Leapmotor',
    'Lexus',
    'Li Auto',
    'Lifan',
    'Ligier',
    'Lincoln',
    'Lotus',
    'Lucid',
    'Lynk & Co',
    'Mahindra',
    'Maruti Suzuki',
    'Maserati',
    'Massey Ferguson',
    'Mazda',
    'Mercedes-Benz',
    'Mercury',
    'MG',
    'MGA',
    'Microcar',
    'Mini',
    'Mitsubishi',
    'Mitsuoka',
    'Modenas',
    'Moto Guzzi',
    'Naza',
    'New Holland',
    'NIO',
    'Nissan',
    'Ola Electric',
    'Olda',
    'Oldsmobile',
    'Omoda',
    'Opel',
    'Perodua',
    'Peugeot',
    'Piaggio',
    'Plymouth',
    'Polestar',
    'Pontiac',
    'Porsche',
    'Portaro',
    'Proton',
    'QJ Motor',
    'Ram',
    'Renault',
    'Rivian',
    'Roewe',
    'Rolls-Royce',
    'Rover',
    'Royal Enfield',
    'Saab',
    'Sado',
    'Saturn',
    'Scion',
    'SEAT',
    'Shineray',
    'Skoda',
    'Smart',
    'Solis',
    'SsangYong',
    'Subaru',
    'Suzuki',
    'Syrena',
    'Tank',
    'Tata',
    'Tesla',
    'Toyota',
    'Triumph',
    'Troller',
    'Trumpchi',
    'TVS',
    'UMM',
    'Valtra',
    'Vauxhall',
    'Veeco',
    'Vento',
    'Vespa',
    'Voge',
    'Volkswagen',
    'Volvo',
    'Voyah',
    'Wuling',
    'Xiaomi',
    'XPeng',
    'Yamaha',
    'Zeekr',
    'Zontes',
  ];
}
