const minLineCoveragePercent = 90.0;

class LineCoverage {
  const LineCoverage({required this.linesFound, required this.linesHit});

  final int linesFound;
  final int linesHit;

  double get percent {
    if (linesFound == 0) {
      return 0;
    }
    return (linesHit / linesFound) * 100;
  }

  bool meetsMinimum(double minimumPercent) => percent >= minimumPercent;
}

LineCoverage parseLcov(String source) {
  var linesFound = 0;
  var linesHit = 0;
  var skipRecord = false;

  for (final line in source.split('\n')) {
    if (line.startsWith('SF:')) {
      skipRecord = _isGeneratedLocalizationFile(line.substring(3).trim());
      continue;
    }
    if (skipRecord) {
      continue;
    }
    linesFound += _metricValue(line, 'LF:');
    linesHit += _metricValue(line, 'LH:');
  }

  return LineCoverage(linesFound: linesFound, linesHit: linesHit);
}

/// Generated by `flutter gen-l10n` (gitignored). Do not count toward the gate.
bool _isGeneratedLocalizationFile(String sourceFile) {
  final fileName = sourceFile.replaceAll(r'\', '/').split('/').last;
  return fileName.startsWith('app_localizations') && fileName.endsWith('.dart');
}

int _metricValue(String line, String prefix) {
  if (!line.startsWith(prefix)) {
    return 0;
  }
  return int.parse(line.substring(prefix.length));
}
